const Renderer = {
    render: (data, lang = 'en') => {
        const app = document.getElementById('app');
        app.innerHTML = ''; // Clear loading state

        // Translations for headers
        const T = {
            missionLogs: { en: 'MISSION LOGS', es: 'REGISTROS DE MISIÓN', fr: 'RAPPORTS DE MISSION' },
            technicalArsenal: { en: 'TECHNICAL ARSENAL', es: 'ARSENAL TÉCNICO', fr: 'ARSENAL TECHNIQUE' },
            knowledgeDatabase: { en: 'KNOWLEDGE DATABASE', es: 'BASE DE CONOCIMIENTOS', fr: 'BASE DE CONNAISSANCES' },
            languageModules: { en: 'LANGUAGE MODULES', es: 'MÓDULOS DE IDIOMA', fr: 'MODULES LINGUISTIQUES' },
            systemOverview: { en: 'SYSTEM OVERVIEW', es: 'RESUMEN DEL SISTEMA', fr: 'APERÇU DU SYSTÈME' },
            systemStatus: { en: 'SYSTEM STATUS: ONLINE', es: 'ESTADO DEL SISTEMA: EN LÍNEA', fr: 'ÉTAT DU SYSTÈME : EN LIGNE' },
            lastUpdate: { en: 'LAST UPDATE', es: 'ÚLTIMA ACTUALIZACIÓN', fr: 'DERNIÈRE MISE À JOUR' },
            generatedBy: { en: 'Generated by Antigravity AI', es: 'Generado por Antigravity AI', fr: 'Généré par Antigravity AI' },
            proficiency: { en: 'PROFICIENCY', es: 'COMPETENCIA', fr: 'MAÎTRISE' }
        };

        // Helper to get localized string or fallback
        const getLoc = (obj, key) => obj[key] ? obj[key][lang] : key;

        // 1. Header / Personal Info
        const header = document.createElement('header');
        header.className = 'mb-12 text-center relative';
        header.innerHTML = `
            <div class="relative inline-block group">
                <div class="absolute -inset-1 bg-gradient-to-r from-cyan-400 to-purple-600 rounded-full blur opacity-25 group-hover:opacity-75 transition duration-1000 group-hover:duration-200"></div>
                <img src="${data.personalInfo.profileImage}" alt="Profile" class="relative w-32 h-32 rounded-full border-2 border-cyan-500 mx-auto object-cover shadow-[0_0_20px_rgba(8,145,178,0.5)]">
            </div>
            <h1 class="text-4xl md:text-6xl font-orbitron font-bold mt-6 text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-500 tracking-wider">${data.personalInfo.name}</h1>
            <h2 class="text-xl md:text-2xl font-rajdhani text-cyan-200 mt-2 tracking-widest uppercase">${data.personalInfo.title}</h2>
            
            <div class="flex flex-wrap justify-center gap-4 mt-6 text-sm font-rajdhani text-gray-400">
                <a href="mailto:${data.personalInfo.email}" class="hover:text-cyan-400 transition-colors flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
                    ${data.personalInfo.email}
                </a>
                <span class="hidden md:inline text-gray-600">|</span>
                <a href="https://${data.personalInfo.website}" target="_blank" class="hover:text-cyan-400 transition-colors flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"></path></svg>
                    ${data.personalInfo.website}
                </a>
                <span class="hidden md:inline text-gray-600">|</span>
                <span class="flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path></svg>
                    ${data.personalInfo.phone}
                </a>
            </div>
        `;
        app.appendChild(header);

        // 2. About Section
        const about = document.createElement('section');
        about.className = 'mb-16 glass-panel p-8 rounded-xl relative overflow-hidden';
        about.innerHTML = `
            <div class="absolute top-0 right-0 p-4 opacity-20">
                <svg class="w-24 h-24 text-cyan-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            </div>
            <h3 class="text-2xl font-orbitron text-cyan-400 mb-4 border-b border-cyan-500/30 pb-2 inline-block">${getLoc(T, 'systemOverview')}</h3>
            <p class="text-gray-300 leading-relaxed font-rajdhani text-lg">
                ${data.aboutDescription[lang] || data.aboutDescription.en} 
            </p>
        `;
        app.appendChild(about);

        // 3. Experience Section
        const experience = document.createElement('section');
        experience.className = 'mb-16';
        experience.innerHTML = `<h3 class="text-3xl font-orbitron text-white mb-8 flex items-center gap-4"><span class="text-cyan-500">>></span> ${getLoc(T, 'missionLogs')}</h3>`;

        const timeline = document.createElement('div');
        timeline.className = 'space-y-8 border-l-2 border-cyan-900 ml-4 pl-8 relative';

        data.experiences.forEach(exp => {
            const item = document.createElement('div');
            item.className = 'relative group';

            // Handle localized period and description
            const period = exp['period_' + lang] || exp.period;
            const descriptions = exp.description[lang] || exp.description.en || [];

            item.innerHTML = `
                <div class="absolute -left-[41px] top-0 w-5 h-5 rounded-full bg-gray-900 border-2 border-cyan-500 group-hover:bg-cyan-500 group-hover:shadow-[0_0_10px_#06b6d4] transition-all duration-300"></div>
                <div class="glass-panel p-6 rounded-lg hover:border-cyan-500/50 transition-all duration-300 transform group-hover:-translate-y-1">
                    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-4">
                        <div>
                            <h4 class="text-xl font-bold text-cyan-300 font-orbitron">${exp.title}</h4>
                            <div class="text-purple-400 font-rajdhani font-bold text-lg">${exp.company}</div>
                        </div>
                        <div class="text-right">
                            <div class="text-cyan-100 font-mono text-sm bg-cyan-900/30 px-3 py-1 rounded border border-cyan-500/30">
                                ${period}
                            </div>
                            <div class="text-gray-500 text-sm mt-1">${exp.location}</div>
                        </div>
                    </div>
                    <ul class="space-y-2">
                        ${descriptions.map(desc => `
                            <li class="flex items-start gap-2 text-gray-300 font-rajdhani">
                                <span class="text-cyan-500 mt-1">›</span>
                                ${desc}
                            </li>
                        `).join('')}
                    </ul>
                </div>
            `;
            timeline.appendChild(item);
        });
        experience.appendChild(timeline);
        app.appendChild(experience);

        // 4. Skills Section
        const skills = document.createElement('section');
        skills.className = 'mb-16';
        skills.innerHTML = `<h3 class="text-3xl font-orbitron text-white mb-8 flex items-center gap-4"><span class="text-cyan-500">>></span> ${getLoc(T, 'technicalArsenal')}</h3>`;

        const skillsGrid = document.createElement('div');
        skillsGrid.className = 'grid grid-cols-1 md:grid-cols-2 gap-8';

        // Helper to render skill category
        const renderSkillCategory = (title, items) => {
            return `
                <div class="glass-panel p-6 rounded-lg">
                    <h4 class="text-lg font-orbitron text-purple-400 mb-4 border-b border-purple-500/30 pb-2">${title}</h4>
                    <div class="flex flex-wrap gap-2">
                        ${items.map(skill => `
                            <span class="px-3 py-1 bg-gray-800 border border-cyan-500/30 rounded text-cyan-300 font-rajdhani text-sm hover:bg-cyan-900/30 hover:border-cyan-400 transition-colors cursor-default">
                                ${skill}
                            </span>
                        `).join('')}
                    </div>
                </div>
            `;
        };

        skillsGrid.innerHTML = `
            ${renderSkillCategory('LANGUAGES', data.skills.languages)}
            ${renderSkillCategory('ANDROID CORE', data.skills.android)}
            ${renderSkillCategory('TOOLS', data.skills.tools)}
            ${renderSkillCategory('METHODOLOGIES', data.skills.methodologies)}
        `;
        skills.appendChild(skillsGrid);
        app.appendChild(skills);

        // 5. Education Section
        const education = document.createElement('section');
        education.className = 'mb-16';
        education.innerHTML = `<h3 class="text-3xl font-orbitron text-white mb-8 flex items-center gap-4"><span class="text-cyan-500">>></span> ${getLoc(T, 'knowledgeDatabase')}</h3>`;

        const eduGrid = document.createElement('div');
        eduGrid.className = 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6';

        data.education.forEach(edu => {
            const card = document.createElement('div');
            card.className = 'glass-panel p-5 rounded-lg border-l-4 border-l-purple-500 hover:bg-gray-800/50 transition-colors';
            card.innerHTML = `
                <div class="flex justify-between items-start mb-2">
                    <span class="text-xs font-mono text-cyan-500 border border-cyan-500/30 px-2 py-0.5 rounded">${edu.year}</span>
                    <span class="text-xs text-gray-500 uppercase">${edu.type}</span>
                </div>
                <h4 class="text-white font-bold font-rajdhani leading-tight mb-1">${edu.title}</h4>
                <div class="text-gray-400 text-sm">${edu.institution}</div>
            `;
            eduGrid.appendChild(card);
        });
        education.appendChild(eduGrid);
        app.appendChild(education);

        // 6. Languages Section
        const languages = document.createElement('section');
        languages.className = 'mb-16';
        languages.innerHTML = `<h3 class="text-3xl font-orbitron text-white mb-8 flex items-center gap-4"><span class="text-cyan-500">>></span> ${getLoc(T, 'languageModules')}</h3>`;

        const langGrid = document.createElement('div');
        langGrid.className = 'grid grid-cols-1 md:grid-cols-3 gap-6';

        data.languages.forEach(l => {
            const card = document.createElement('div');
            card.className = 'glass-panel p-6 rounded-lg text-center relative overflow-hidden';
            card.innerHTML = `
                <div class="absolute bottom-0 left-0 h-1 bg-gradient-to-r from-cyan-500 to-purple-500 transition-all duration-1000" style="width: ${l.proficiency}%"></div>
                <h4 class="text-xl font-orbitron text-white mb-1">${l.name}</h4>
                <div class="text-cyan-400 font-rajdhani text-lg font-bold">${l.level}</div>
                <div class="text-gray-600 text-xs mt-2 font-mono">${getLoc(T, 'proficiency')}: ${l.proficiency}%</div>
            `;
            langGrid.appendChild(card);
        });
        languages.appendChild(langGrid);
        app.appendChild(languages);

        // Footer
        const footer = document.createElement('footer');
        footer.className = 'text-center text-gray-600 text-sm py-8 font-mono border-t border-gray-800 mt-12';
        footer.innerHTML = `
            <p>${getLoc(T, 'systemStatus')}</p>
            <p>${getLoc(T, 'lastUpdate')}: ${new Date(data.updated_at).toLocaleDateString()}</p>
            <p class="mt-2">${getLoc(T, 'generatedBy')}</p>
        `;
        app.appendChild(footer);
    }
};
